name: lando-heroku
recipe: mean
config:
  webroot: public

services:
 mongoservice:
   type: mongo
   portforward: true
 nodeservice:
   type: node
   build:
    - npm install
   command: npm start server.js
   port: 5000

tooling:
  heroku:
    service: appserver
    cmd: /usr/bin/heroku