name: lando-heroku-sockets
recipe: mean
config:
  webroot: public
  node: 14
  build:
    - npm install
<<<<<<< HEAD
  command: npm start  
=======
  command: npm start
>>>>>>> b4b7f29accdd9cebaddfb809772cc35e4392e23a
  port: 5000

services:
 appserver:
   extras:
    - "wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh"
   build_as_root:  
<<<<<<< HEAD
    - "wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip -O temp.zip"
    - "unzip temp.zip -d /usr/local/bin"
    - "chmod a+x /usr/local/bin/tweego"
=======
    - "wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip -O temp.zip && unzip temp.zip -d /usr/local/bin && rm temp.zip && chmod a+x /usr/local/bin/tweego"
#    - "unzip temp.zip -d /usr/local/bin"
#    - "chmod a+x /usr/local/bin/tweego"

>>>>>>> b4b7f29accdd9cebaddfb809772cc35e4392e23a
tooling:
  heroku:
    service: appserver
    cmd: /usr/bin/heroku