name: lando-heroku-sockets
recipe: mean
config:
  webroot: public

services:
 appserver:
   extras:
    - "wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh"
 mongoservice:
   type: mongo
   portforward: true
 nodeservice:
   type: node
   build:
    - npm install
   command: npm start server.js
   port: 5000

tooling:
  heroku:
    service: appserver
    cmd: /usr/bin/heroku